import { DATA_EXPORT_QUERY_COLUMNS } from './data-columns';

const query = `SELECT ${DATA_EXPORT_QUERY_COLUMNS.join(', ')} FROM COST_AND_USAGE_REPORT`;

import { BCMDataExportsClient, CreateExportCommand, CreateExportCommandInput } from '@aws-sdk/client-bcm-data-exports'; // ES Modules import

const client = new BCMDataExportsClient({});
const input1: CreateExportCommandInput = {
  // CreateExportRequest
  Export: {
    // Export
    Name: 'Scripted_CUR', // required
    Description: 'This is a CUR generated by a script from Ollion',
    DataQuery: {
      // DataQuery
      QueryStatement: query, // required
      TableConfigurations: {
        // TableConfigurations
        COST_AND_USAGE_REPORT: {
          INCLUDE_MANUAL_DISCOUNT_COMPATIBILITY: 'FALSE',
          INCLUDE_RESOURCES: 'TRUE',
          INCLUDE_SPLIT_COST_ALLOCATION_DATA: 'TRUE',
          TIME_GRANULARITY: 'HOURLY',
        },
      },
    },
    DestinationConfigurations: {
      // DestinationConfigurations
      S3Destination: {
        // S3Destination
        S3Bucket: 'bucket-name', // required
        S3Prefix: 'scripted_cur', // required
        S3Region: 'us-east-1',
        S3OutputConfigurations: {
          // S3OutputConfigurations
          OutputType: 'CUSTOM', // required
          Format: 'PARQUET', // required
          Compression: 'PARQUET', // required
          Overwrite: 'OVERWRITE_REPORT', // required
        },
      },
    },
    RefreshCadence: {
      // RefreshCadence
      Frequency: 'SYNCHRONOUS', // required
    },
  },
};
const command = new CreateExportCommand(input1);

// client
//   .send(command)
//   .then((resp) => console.log(JSON.stringify(resp, null, 2)))
//   .catch((err) => console.error(err));
